[package]
name = "realm"
version = "1.5.0"
authors = ["zhboner <zhboner@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1"
futures = "0.3"
log = "0.4"

clap = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

tokio = { version = "1", features = ["rt", "rt-multi-thread", "io-util", "net", "time"] }
trust-dns-resolver = { version = "0.20", optional = true }

lazy_static = "1"

# tfo
tokio-tfo = { git = "https://github.com/zephyrchien/tokio-tfo", branch = "main", version = "0.1.6", optional = true }

# zero-copy
libc = { version = "0.2", optional = true }

#logger
chrono = "0.4"
fern = "0.6"
env_logger = { version = "0.9", optional = true }

[target.'cfg(unix)'.dependencies]
daemonize = "0.4"

[profile.release]
opt-level = 3
lto = true

[profile.dev]
opt-level = 0

[features]
default = ["udp", "zero-copy", "trust-dns"]
udp = []
tfo = ["tokio-tfo"]
zero-copy = ["libc"]
trust-dns = ["trust-dns-resolver"]
x-debug = ["env_logger"]

[dev-dependencies]
env_logger = "0.9"
